### ISSUE TITLE
PDNS hang issue with lightningstream and containers

### ISSUE THREAD

**Issue by mschirrmeister** [PowerDNS/lightningstream#75]
I was playing with PowerDNS and Lightningstream in Kubernetes and ran into a very weird issue. It is a StatefulSet and storage comes from Longhorn. 
PowerDNS auth and Lightningstream are both the latest versions and it is running on **ARM64**.

The issue is that a query to **pdns** (dns or rest api) hangs and returns nothing. Executing the `pdnsutil` tool on the pdns container hangs as well. Like `pdnsutil list-all-zones` hangs and the prompt never returns.
Even with debug logging, there is no error. It shows the incoming request and that it is processing, but no answer is returned.

First I thought it is related to the pid clashing issue for containers that is mentioned in the docs. But it does **not** matter what I use for `--minimum-pid`, the issue persisted.

The issue goes away, if I send a dns query to PDNS for a **valid** record/zone before lightningstream is started. So the _command_ in my lightingstream container is a shell script, which first sends a DNS query to the pdns container and then starts lightning stream.

It still looks somewhat like a locking issue, but the question is what is different internally how pdns auth server accesses the LMDB backend when there was a dns request to pdns before lightningstream is started vs when there was no request?

It runs stable with no issues so far with the workaround. 

Do you have any input on what could be going on here?

Configurations listed below.

My `pdns.conf` looks like this.
```
pdns@pdns-ss-0:/$ cat /etc/powerdns/pdns.conf
primary=yes
allow-notify-from=0.0.0.0
allow-axfr-ips=127.0.0.1
api=yes
api-key=secret
config-dir=/etc/powerdns
default-soa-content=a.misconfigured.dns.server.invalid hostmaster.@ 0 10800 3600 604800 3600
default-ttl=3600
default-ksk-algorithm=ed25519
default-zsk-algorithm=ed25519
include-dir=/etc/powerdns/pdns.d
load-modules=liblmdbbackend.so
launch=lmdb
lmdb-filename=/var/lib/powerdns/pdns.lmdb
lmdb-shards=1
lmdb-sync-mode=nometasync
lmdb-schema-version=5
lmdb-random-ids=yes
lmdb-map-size=1000
lmdb-flag-deleted=yes
lmdb-lightning-stream=yes
local-address=0.0.0.0,::
log-dns-details=yes
log-dns-queries=yes
log-timestamp=yes
loglevel=7
loglevel-show=yes
query-logging=yes
resolver=1.1.1.1
# server-id
version-string=anonymous
webserver=yes
webserver-allow-from=127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,192.0.0.0/24
webserver-hash-plaintext-credentials=yes
webserver-loglevel=detailed
webserver-address=0.0.0.0
webserver-port=8081
webserver-password=secret2
zone-cache-refresh-interval=0
zone-metadata-cache-ttl=0
```

My `lightningstream.yaml` looks like this.
```
/app $ cat /lightningstream.yaml
instance: lmdbsync
storage_poll_interval: 10s
lmdb_poll_interval: 10s
storage_force_snapshot_interval: 4h

lmdbs:
  main:
    path: /var/lib/powerdns/pdns.lmdb
    schema_tracks_changes: true
    options:
      no_subdir: true
      create: false
  shard:
    path: /var/lib/powerdns/pdns.lmdb-0
    schema_tracks_changes: true
    options:
      no_subdir: true
      create: false

storage:
  type: s3
  options:
    access_key: pdns
    secret_key: pdns
    bucket: lightningstream
    endpoint_url: http://10.0.3.194:9000
    create_bucket: true
  cleanup:
    enabled: true
    interval: 15m
    must_keep_interval: 24h
    remove_old_instances_interval: 168h

http:
  address: ":8500"

log:
  level: info
  format: human
  timestamp: short
```

My shell script with the workaround:
```
/app $ cat start.sh
#!/bin/sh

if [ ${PDNS_LSTREAM_SLEEP}_ == _ ]; then
    echo "no sleep time set"
else
    sleep ${PDNS_LSTREAM_SLEEP}
fi

if [ ${PDNS_LSTREAM_DNS_SERVER}_ == _ ]; then
    echo "no DNS server set"
else
    eval DNS=\$$PDNS_LSTREAM_DNS_SERVER
    echo "ServiceIP: $DNS"
    echo "PodIP: $PDNS_POD_IP"
    dig @$PDNS_POD_IP $PDNS_LSTREAM_DOMAIN $PDNS_QUERY_TYPE
fi

/app/lightningstream --config /app/lightningstream.yaml --minimum-pid 200 --instance ${HOSTNAME}-lstream sync
```

**Comment by joel-ling** [comment]
Hello @mschirrmeister, thank you for describing the intriguing phenomenon and its workaround.

As it appears to have played out on a complex setup with many moving parts, we would be stoked if some variables could be excluded/isolated, so as to cut down the search space containing all probable causes.

Since the use of Longhorn introduces many abstractions and interactions, the effects of which on LMDB is yet to be determined, we are curious to learn if you could reproduce the issue on a simpler setup, sans Longhorn.

Any information you could provide about the following could also turn out to be valuable:
* The filesystem on the Longhorn volume, e.g. the value of parameter `fsType` of the relevant StorageClass
* The StatefulSet, PersistentVolumeClaim, and other relevant Kubernetes objects, e.g. in YAML format

(We note that you may be using the Dockerfile in your [public repository](https://github.com/mschirrmeister/powerdns-lightningstream-docker/tree/main) mentioning the same issue.)

Also highly interesting is the PID-clash hypothesis, considering that LMDB locking appears to be keyed on PIDs. Could you please verify that the Lightning Stream process started with the `--minimum-pid` option indeed does not share a process ID with the Authoritative Nameserver?

[This article](https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/) about having containers in a Pod share a process namespace presents an alternative means of resolving the PID conflict that might be worth an attempt.

Finally, would you mind sharing your thoughts on the following bullet points under the Caveats section of the [LMDB docs](http://www.lmdb.tech/doc/)?

> * Do not use LMDB databases on remote filesystems, even between processes on the same host. This breaks flock() on some OSes, possibly memory map sync, and certainly sync between programs on different hosts.
>
> * Opening a database can fail if another process is opening or closing it at exactly the same time.

We look forward to hearing your response.

**Comment by wojas** [comment]
Note that `create: false` is used in Lightning Stream, which means that it expects the LMDB to be created by pdns. The query you perform against pdns may be the trigger to create this LMDB.

Suggestions:

- Run a pdnsutil command in an initContainer to create the actual LMDB before any service is started.
- Ensure that both services run as the same user and that filesystem permissions are set correctly.

**Comment by wojas** [comment]
Additionally, it is essential that Auth and LS run on the same node with a local filesystem for the LMDB, ideally tmpfs. In a cloud deployment it is S3 that provides your persistent data store, not the LMDB.

**Comment by mschirrmeister** [comment]
Here are my files and some context.

I use a StatefulSet that all containers in a pod are scheduled on the **same** node and that each pod, if scaled up, is scheduled on a **different** node.

I also wanted to use **existing** disks for the pods, since I want that the data survives if pods get deleted.
Therefore I use `volumeClaimTemplates` in the StatefulSet which gives predictable names for the `PersistentVolumeClaims`.
The 3 `PersistentVolumes` reference these names in `claimRef`.

In Longhorn I created 3 volumes `pdns-ss-data-0`, `pdns-ss-data-1` and `pdns-ss-data-2`, which are referenced in the PV under `volumeHandle`

With this config, you can apply, delete or scale up/down (up to 3) the StatefulSet and it will always use the same disks. I think that is how it is done typically for databases.


`storageclass-nfs.yaml`

```
# This storage class creates a durable pv for RWX volumes
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-nfs    
provisioner: driver.longhorn.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "disabled"
  nfsOptions: "vers=4.2,noresvport,intr,hard,softerr,timeo=600,retrans=5,local_lock=flock"
```

`pdns-auth-configmap-202405041.yaml`

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-pdns-auth-202405041
  namespace: pdns
data:
  pdns.conf: |
    primary=yes
    allow-notify-from=0.0.0.0
    allow-axfr-ips=127.0.0.1
    api=yes
    api-key=secret
    config-dir=/etc/powerdns
    default-soa-content=a.misconfigured.dns.server.invalid hostmaster.@ 0 10800 3600 604800 3600
    default-ttl=3600
    default-ksk-algorithm=ed25519
    default-zsk-algorithm=ed25519
    include-dir=/etc/powerdns/pdns.d
    load-modules=liblmdbbackend.so
    launch=lmdb
    lmdb-filename=/var/lib/powerdns/pdns.lmdb
    lmdb-shards=1
    lmdb-sync-mode=nometasync
    lmdb-schema-version=5
    lmdb-random-ids=yes
    lmdb-map-size=1000
    lmdb-flag-deleted=yes
    lmdb-lightning-stream=yes
    # launch=gsqlite3
    # gsqlite3-database=/var/lib/powerdns/pdns.sqlite3
    local-address=0.0.0.0,::
    log-dns-details=yes
    log-dns-queries=yes
    log-timestamp=yes
    # 0 = emergency, 1 = alert, 2 = critical, 3 = error, 4 = warning, 5 = notice, 6 = info, 7 = debug
    loglevel=4
    loglevel-show=yes
    query-logging=yes
    # resolver=blocky.blocky.svc.cluster.local
    # resolver=10.43.226.25
    resolver=1.1.1.1
    # server-id
    version-string=anonymous
    webserver=yes
    webserver-allow-from=127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,192.0.0.0/24
    webserver-hash-plaintext-credentials=yes
    # one of "none", "normal", "detailed"
    webserver-loglevel=normal
    webserver-address=0.0.0.0
    webserver-port=8081
    webserver-password=secret2
    zone-cache-refresh-interval=0
    zone-metadata-cache-ttl=0
```

`pdns-lightningstream-configmap-202405102.yaml`

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-lightningstream-202405102
  namespace: pdns
data:
  lightningstream.yaml: |
    instance: lmdbsync
    storage_poll_interval: 10s
    lmdb_poll_interval: 10s
    storage_force_snapshot_interval: 4h

    lmdbs:
      main:
        path: /var/lib/powerdns/pdns.lmdb
        schema_tracks_changes: true
        options:
          no_subdir: true
          create: false
      shard:
        path: /var/lib/powerdns/pdns.lmdb-0
        schema_tracks_changes: true
        options:
          no_subdir: true
          create: false

    storage:
      type: s3
      options:
        access_key: pdns
        secret_key: pdns#112
        bucket: lightningstream
        endpoint_url: http://minio.minio.svc.cluster.local:9000
        create_bucket: true
      cleanup:
        enabled: true
        interval: 15m
        must_keep_interval: 24h
        remove_old_instances_interval: 168h

    http:
      address: ":8500"

    log:
      level: info
      format: human
      timestamp: short
```

`pdns-lightningstream-start-configmap-202405111.yaml`

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-lightningstream-start-202405111
  namespace: pdns
data:
  start.sh: |
    #!/bin/sh

    if [ ${PDNS_LSTREAM_SLEEP}_ == _ ]; then
        echo "no sleep time set"
    else
        sleep ${PDNS_LSTREAM_SLEEP}
    fi

    if [ ${PDNS_LSTREAM_DNS_SERVER}_ == _ ]; then
        echo "no DNS server set"
    else
        eval DNS=\$$PDNS_LSTREAM_DNS_SERVER
        echo "ServiceIP: $DNS"
        echo "PodIP: $PDNS_POD_IP"
        dig @$PDNS_POD_IP $PDNS_LSTREAM_DOMAIN $PDNS_QUERY_TYPE
    fi

    # seq 210 | xargs -Iz echo "Generating pids. Count z"
    /app/lightningstream --config /lightningstream.yaml --minimum-pid 200 --instance ${HOSTNAME}-lstream sync
```

`pdns-statefulset-nfs-all.yaml`

```
apiVersion: v1
kind: Namespace
metadata:
  name: pdns
  labels:
    name: pdns
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pdns-ss-pv-data-nfs-0
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: pdns
    name: pdns-ss-vol-nfs-pdns-ss-0
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: pdns-ss-data-0
  storageClassName: longhorn-nfs
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pdns-ss-pv-data-nfs-1
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: pdns
    name: pdns-ss-vol-nfs-pdns-ss-1
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: pdns-ss-data-1
  storageClassName: longhorn-nfs
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pdns-ss-pv-data-nfs-2
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: pdns
    name: pdns-ss-vol-nfs-pdns-ss-2
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: pdns-ss-data-2
  storageClassName: longhorn-nfs
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pdns-ss
  namespace: pdns
  labels:
    app.kubernetes.io/name: pdns-ss
spec:
  persistentVolumeClaimRetentionPolicy:
    whenScaled: Retain
    whenDeleted: Delete
  replicas: 1
  selector:
    matchLabels:
      app: pdns-ss
  serviceName: pdns-ss
  template:
    metadata:
      labels:
        app: pdns-ss
        app.kubernetes.io/name: pdns-ss
    spec:
      securityContext:
        fsGroup: 953
        runAsUser: 953
        runAsGroup: 953
      containers:
      - name: pdns-ss
        # image: powerdns/pdns-auth-49:4.9.0
        image: mschirrmeister/pdns-auth:master
        env:
        - name: TZ
          value: "Europe/Berlin"
        ports:
          - containerPort: 53
            protocol: TCP
          - containerPort: 53
            protocol: UDP
          - containerPort: 8081
            protocol: TCP
        volumeMounts:
        - name: config
          mountPath: "/etc/powerdns/pdns.conf"
          subPath: pdns.conf
        - name: resolver-config
          mountPath: "/etc/powerdns/pdns.d"
        - name: pdns-ss-vol-nfs
          mountPath: /var/lib/powerdns
      - name: pdns-lightningstream
        image: mschirrmeister/powerdns-lightningstream:v0.4.3
        env:
        - name: PDNS_LSTREAM_DNS_SERVER
          value: PDNS_SS_SERVICE_HOST
        - name: PDNS_LSTREAM_SLEEP
          value: "1"
        - name: PDNS_LSTREAM_DOMAIN
          value: "dummy.zone"
        - name: PDNS_QUERY_TYPE
          value: SOA
        - name: PDNS_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        command: [ "/app/start.sh" ]
        volumeMounts:
        - name: pdns-ss-vol-nfs
          mountPath: /var/lib/powerdns
          readOnly: false
        - name: config-lightningstream
          mountPath: "/lightningstream.yaml"
          subPath: lightningstream.yaml
        - name: config-lightningstream-start
          mountPath: "/app/start.sh"
          subPath: start.sh
      # - name: debug-container
      #   image: alpine:latest
      #   imagePullPolicy: Always
      #   args: ["tail", "-f", "/dev/null"]
      #   volumeMounts:
      #   - name: pdns-ss-vol
      #     mountPath: /var/lib/powerdns
      #     # readOnly: true
      restartPolicy: Always
      volumes:
      - name: config
        configMap:
          name: app-config-pdns-auth-202405041
          items:
          - key: "pdns.conf"
            path: "pdns.conf"
      - name: config-lightningstream
        configMap:
          name: app-config-lightningstream-202405102
          items:
          - key: "lightningstream.yaml"
            path: "lightningstream.yaml"
      - name: config-lightningstream-start
        configMap:
          name: app-config-lightningstream-start-202405111
          items:
          - key: "start.sh"
            path: "start.sh"
          defaultMode: 0755
      - name: resolver-config
        emptyDir: {}
      initContainers:
      - name: pdns-resolver-config
        image: jonlabelle/network-tools
        command: [ "sh" ]
        # args: [ "-c", "echo resolver=`dig blocky.blocky.svc.cluster.local +short` > /resolver-config/resolver.conf" ]
        args: [ "-c", "echo" ]
        volumeMounts:
        - name: resolver-config
          mountPath: /resolver-config
  volumeClaimTemplates:
  - metadata:
      name: pdns-ss-vol-nfs
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 1Gi
      storageClassName: longhorn-nfs
---
apiVersion: v1
kind: Service
metadata:
  name: pdns-ss
  namespace: pdns
  annotations:
    metallb.universe.tf/address-pool: second-pool
    pdns.prometheus/scrape: "true"
    pdns.prometheus/scheme: "http"
    pdns.prometheus/path: "/metrics"
    pdns.prometheus/port: "8081"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  # externalTrafficPolicy: Local
  selector:
    app: pdns-ss
  ports:
    - name: dnstcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: dnsudp
      protocol: UDP
      port: 53
      targetPort: 53
    - name: pdnshttp
      protocol: TCP
      port: 8081
      targetPort: 8081
```
